
    CREATE TABLE IF NOT EXISTS masterlist_26_30 (
        "Index" integer,
        "congressman" character varying(255),
        "governor" character varying(255),
        "mayor" character varying(255),
        "region" character varying(100),
        "division" character varying(100),
        "school_id" character varying(50),
        "lis_nsbi_school_id_24_25" character varying(50),
        "in_masterlist_with_gov" character varying(50),
        "school_name" text,
        "municipality" character varying(100),
        "leg_district" character varying(100),
        "priority_index" numeric,
        "cl_requirement" integer,
        "estimated_classroom_shortage" integer,
        "no_of_sites" integer,
        "proposed_no_of_classrooms" integer,
        "no_of_unit" integer,
        "sty" integer,
        "cl" integer,
        "proposed_scope_of_work" text,
        "number_of_workshops" text,
        "workshop_types" text,
        "other_design_configurations" text,
        "proposed_funding_year" integer,
        "est_cost_of_classrooms" numeric,
        "project_implementor" character varying(255),
        "cl_sty_ratio" character varying(50)
    );
